### ISSUE TITLE
Adding Support For the MVAPICH2 Software

### ISSUE THREAD

**Issue by BTMichalowicz** [gvallee/go_hpc_jobmgr#11]
Per our email chain with the OpenHPCA benchmark suite with Geoffroy and issue #34 on the OpenHPCA repository, any/all discussion for adding MVAPICH2 support to go_hpc_jobmgr will be placed here.

**Comment by gvallee** [comment]
Thanks for following up on this. I would need the following information to create `pkg/mvapich2/mvapich2`:
- What are the best `mpirun` parameters to use, sort of the best practices? For instance, with Open MPI, it is best practice to use UCX so the package has all the parameters to ensure UCX in used as default for Open MPI. This is the `GetExtraMpirunArgs()` function in `pkg/openmpi/openmpi.go`.
- What is the best way to detect that MVAPICH is the MPI in a install directory (so the directory usually specify for `--prefix`)? It also needs to return the version of MVAPICH. This is the `DetectFromDir()` function in `pkg/openmpi/openmpi.go`.

I will shortly create a branch to work on this and prepare the basic code that is required.

**Comment by gvallee** [comment]
The PR is WIP, atm it only adds the very basic code that is required. With the answer to the two questions, it will be easy to finalize the PR.

**Comment by BTMichalowicz** [comment]
No problem! 

To answer the first question: 
The main things to set are as follows:
`MV2_HOMOGENEOUS_CLUSTER=1` -- this will drastically reduce startup time provided a person isn't running on, e.g. a CPU/DPU combination
`MV2_USE_RDMA_CM=0`

The MVAPICH team recommends using the following binding/mapping setup (See https://mvapich.cse.ohio-state.edu/static/media/mvapich/mvapich2-userguide.pdf (MVAPICH2-2.3.7 userguide, pages 64-67 for more details)
`MV2_CPU_BINDING_POLICY=hybrid`
`MV2_HYBRID_BINDING_POLICY=spread`

-----------------------

To answer the second question: Version number and configure options (among other information) can be found with the `mpichversion` and `mpiname` binaries found inside `/path/to/install/bin`, though some string parsing will have to be done to isolate the build directory from the configuration options as far as I can tell.

I hope this helps!

**Comment by gvallee** [comment]
I will need your help for this, unfortunately, i do not have the time to install MVAPICH, read the documentation (I never ever used it before), do the extension and test everything.

Could you please provide the exact `mpichversion` and the output? I think it is all that is required for the code to detect the version.

As for the environment variables, the package current assumes that parameters can be set on the command line. It would be easy to extent it with environments variables but it is current available.

**Comment by BTMichalowicz** [comment]
@gvallee No worries! 

Here's an output of the `mpichversion` I used -- I believe the path is in the tarball/zipped file outputs I sent you, since I built this in my scratch directory on HPCAC. 

Path to it: `/global/scratch/users/benjaminm/Geoffroy-OpenHPCA-benchmark-work/mv2-2.3.7/install/bin/mpichversion`
Output:
```
MVAPICH2 Version:       2.3.7
MVAPICH2 Release date:  Wed March 02 22:00:00 EST 2022
MVAPICH2 Device:        ch3:mrail
MVAPICH2 configure:     --prefix=/global/scratch/users/benjaminm/Geoffroy-OpenHPCA-benchmark-work/mv2-2.3.7/install CC=gcc CXX=g++ --disable-fortran --enable-fast=all --enable-g=none --with-device=ch3:mrail CFLAGS=-lpthread LDFLAGS=-lpthread
MVAPICH2 CC:    gcc -lpthread   -DNDEBUG -DNVALGRIND -O2
MVAPICH2 CXX:   g++   -DNDEBUG -DNVALGRIND -O2
MVAPICH2 F77:   gfortran
MVAPICH2 FC:    gfortran
```
I can chmod the install directory for you to use (`/global/scratch/users/benjaminm/Geoffroy-OpenHPCA-benchmark-work/mv2-2.3.7/install/`), if you'd like? That way, you're able to access any/all compiled binaries.

For the environment variables, these parameters CAN be set on the command line `mpirun -np .... -genv <var>=<val> ./app`  as opposed to OpenMPI's `-x` flag.  Not sure how much that will impact things at runtime.

**Comment by gvallee** [comment]
Awesome, thanks! Let me have a first shot at the code based on this and we can then see what is the best way to move forward. I am not opposed in trying to use the install you have but it is a little premature i think.

**Comment by BTMichalowicz** [comment]
Sounds good!

**Comment by gvallee** [comment]
@BTMichalowicz I finished the code to detect MVAPICH so could you please checkout the PR and try with one of your installs (after running `make`)?
```
./cmd/mpi_detect/mpi_detect -dir <PATH_TO_INSTALL_DIR>
```

You should see something like:
```
mvapich2 2.3.7
```

**Comment by BTMichalowicz** [comment]
Hi @gvallee ,

Thank you! Right now, I see the following:

![image](https://user-images.githubusercontent.com/27008062/193065122-bc90172c-fb2e-492e-b05a-76bbaf4b4f9f.png)

Because MVAPICH2 is built over MPICH, use of `mpirun --version` will present us with the MPICH version number. We ( the lab )has developed a modified launcher (`mpirun_rsh`) that will provide the "right" version via `mpirun_rsh -v`.

My apologies for the confusion! Let me know how I or the MVAPICH2 team can help on this issue.

**Comment by gvallee** [comment]
@BTMichalowicz No problem at all, it is part of the problem. Could you please the changes I just pushed? Also, I added the list of default parameters for `mpirun`, in the `GetExtraMpirunArgs()` function. Could you please review them? Thanks

**Comment by BTMichalowicz** [comment]
@gvallee Just checked -- the latest changes look good to me.

**Comment by BTMichalowicz** [comment]
Hi @gvallee,

Sorry to bother you on the weekend. It seems that even though `mpirun_rsh` is detected in the targetBin path inside mvapich2.go, I noticed that it seems to be overridden by something else, hence why it calls `mpirun` instead of `mpirun_rsh`

**Comment by BTMichalowicz** [comment]
Update: Just needed to swap MVAPICH2's and MPICH's `DetectFromDir()` modules. Just tried this out: 

```
[benjaminm@helios001 go_hpc_jobmgr]$ git diff
diff --git a/pkg/mpi/mpi.go b/pkg/mpi/mpi.go
index 8517fb1..2910c6d 100644
--- a/pkg/mpi/mpi.go
+++ b/pkg/mpi/mpi.go
@@ -102,14 +102,14 @@ func DetectFromDir(dir string) (implem.Info, error) {
                m.InstallDir = dir
                return m, nil
        }
-       id, version, err = mpich.DetectFromDir(dir, nil)
+       id, version, err = mvapich2.DetectFromDir(dir, nil)
        if err == nil {
                m.ID = id
                m.Version = version
                m.InstallDir = dir
                return m, nil
        }
-       id, version, err = mvapich2.DetectFromDir(dir, nil)
+       id, version, err = mpich.DetectFromDir(dir, nil)
        if err == nil {
                m.ID = id
                m.Version = version
@@ -117,5 +117,6 @@ func DetectFromDir(dir string) (implem.Info, error) {
                return m, nil
        }

+
        return m, fmt.Errorf("unable to detect any supported MPI implementation from %s", dir)
 }
```

Seems that it checks out since MVAPICH2 is built upon MPICH --> MPICH's `mpirun` was found within it.

**Comment by gvallee** [comment]
@BTMichalowicz Thanks and done. Did you have a chance to have a look at the default `mpirun` parameters? If they are ok, we can release a new version of the package.
